- hosts: localhost
  gather_facts: no

  tasks:
    - include_vars: vars/userlist.yml

    - include: users.yml
      vars:
        user: "{{ item.name }}"
        port: "{{ item.port }}"
        # password is "ansible-itc"
        password: "$6$rounds=656000$OLg7NBkmbfAiDoss$/6POpB8cxH17ZG3X8YuN8156orj4xgKaVxqgFWJANH2r9sjz7pL.RFcIlQhNN635QpiFpQgu6ryGK5dHeEXYT."
        ldir: lesson2_files
      with_items:
        - "{{ group }}"

    - shell: /root/ansible_lesson2/dockerfile/create_proxy.sh chdir=dockerfile/ creates=myproxy

    - include: rproxy.yml
